--NULL
--  todos los usuarios con el correo nulo 
select *
FROM users 
WHERE email IS NULL;


--  TODOS LOS USUARIOS SIN EL CORREO NULO 

SELECT *
FROM users 
WHERE email IS NOT NULL AND age > 25;

-- IFNULL
-- ES UNA DUNCION QUE NOS PERMITE REMPLAZAR EL VALOR NULO POR OTRO VALOR QUE YA LO INDIQUE 
-- OBTENER EL NOMBRE, APELLIDO Y EDAD DE LA TABLA USERS Y SI LA EDAD ES NULA REMPLACELA POR 0
SELECT name, last_name, IFNULL(age,0) AS age 
FROM users

