print("elige 3 productos de la tienda digital")
producto1 = input("Escriba el nombre del producto 1: ")
producto2 = input("Escriba el nombre del producto 2: ")
producto3 = input("Escriba el nombre del producto 3: ")
print(f"Los productos que el cliente eligio son: {producto1}, {producto2} y {producto3}")   
print("cual es el precio y disponibilidad de inventario de cada producto?")
print(f"el precio   {producto1} es: 5 quetzales ")
print(f"el precio   {producto2} es: 7.50 quetzales ")
print(f"el precio    {producto3} es: 8.90 quetzles ")
#inevntario
print(f"el producto {producto1} tiene 10 unidades disponibles en inventario")
print(f"el producto {producto2} tiene 5 unidades disponibles en inventario")         
print(f"el producto {producto3} tiene 2 unidades disponibles en inventario")         